name: cargo test

on:
  push:
    branches: ["wf-test"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: cargo test
        run: cargo test --verbose
      - name: cargo test --features atfork
        run: cargo test --verbose --features atfork
