name: Rust

on:
  workflow_dispatch:
  push:
    branches: ["wf-test"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
      - name: Run tests with atfork
        run: cargo test --verbose --features atfork
